In [1]:
#!pip install statsmodels
#!pip install scipy

In [2]:
#import the libraries
import pandas as pd
import numpy as np
%matplotlib inline
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols


In [ ]:
# Read Sales.Dirty.xls
salesdf = pd.read_excel('sales_data.xls')

In [4]:
salesdf.dtypes

Row ID                           int64
Order ID                         int64
Order Date              datetime64[ns]
Order Priority                  object
Order Quantity                   int64
Sales                          float64
Discount                       float64
Ship Mode                       object
Profit                         float64
Unit Price                     float64
Shipping Cost                  float64
Customer Name                   object
Province                        object
Region                          object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Name                    object
Product Container               object
Product Base Margin            float64
Ship Date               datetime64[ns]
dtype: object

In [5]:
salesdf.shape

(8399, 21)

In [6]:
salesdf.head(10)

Row ID  Order ID Order Date Order Priority  Order Quantity       Sales  \
0       1         3 2010-10-13            Low               6    261.5400   
1      49       293 2012-10-01           High              49  10123.0200   
2      50       293 2012-10-01           High              27    244.5700   
3      80       483 2011-07-10           High              30   4965.7595   
4      85       515 2010-08-28  Not Specified              19    394.2700   
5      86       515 2010-08-28  Not Specified              21    146.6900   
6      97       613 2011-06-17           High              12     93.5400   
7      98       613 2011-06-17           High              22    905.0800   
8     103       643 2011-03-24           High              21   2781.8200   
9     107       678 2010-02-26            Low              44    228.4100   

   Discount       Ship Mode     Profit  Unit Price  ...       Customer Name  \
0      0.04     Regular Air  -213.2500       38.94  ...  Muhammed MacIntyre   
1      0.07  Delivery Truck   457.8100      208.16  ...        Barry French   
2      0.01     Regular Air    46.7075        8.69  ...        Barry French   
3      0.08     Regular Air  1198.9710      195.99  ...       Clay Rozendal   
4      0.08     Regular Air    30.9400       21.78  ...      Carlos Soltero   
5      0.05     Regular Air     4.4300        6.64  ...      Carlos Soltero   
6      0.03     Regular Air   -54.0385        7.30  ...        Carl Jackson   
7      0.09     Regular Air   127.7000       42.76  ...        Carl Jackson   
8      0.07     Express Air  -695.2600      138.14  ...      Monica Federle   
9      0.07     Regular Air  -226.3600        4.98  ...     Dorothy Badders   

  Province   Region Customer Segment Product Category  \
0  Nunavut  Nunavut   Small Business  Office Supplies   
1  Nunavut  Nunavut         Consumer  Office Supplies   
2  Nunavut  Nunavut         Consumer  Office Supplies   
3  Nunavut  Nunavut        Corporate       Technology   
4  Nunavut  Nunavut         Consumer  Office Supplies   
5  Nunavut  Nunavut         Consumer        Furniture   
6  Nunavut  Nunavut        Corporate  Office Supplies   
7  Nunavut  Nunavut        Corporate  Office Supplies   
8  Nunavut  Nunavut        Corporate  Office Supplies   
9  Nunavut  Nunavut      Home Office  Office Supplies   

             Product Sub-Category  \
0          Storage & Organization   
1                      Appliances   
2  Binders and Binder Accessories   
3    Telephones and Communication   
4                      Appliances   
5              Office Furnishings   
6  Binders and Binder Accessories   
7          Storage & Organization   
8          Storage & Organization   
9                           Paper   

                                        Product Name Product Container  \
0   Eldon Base for stackable storage shelf, platinum         Large Box   
1  1.7 Cubic Foot Compact "Cube" Office Refrigera...        Jumbo Drum   
2   Cardinal Slant-D® Ring Binder, Heavy Gauge Vinyl         Small Box   
3                                               R380         Small Box   
4                           Holmes HEPA Air Purifier        Medium Box   
5  G.E. Longer-Life Indoor Recessed Floodlight Bulbs        Small Pack   
6  Angle-D Binders with Locking Rings, Label Holders         Small Box   
7            SAFCO Mobile Desk Side File, Wire Frame         Small Box   
8              SAFCO Commercial Wire Shelving, Black         Large Box   
9                                          Xerox 198         Small Box   

  Product Base Margin  Ship Date  
0                0.80 2010-10-20  
1                0.58 2012-10-02  
2                0.39 2012-10-03  
3                0.58 2011-07-12  
4                0.50 2010-08-30  
5                0.37 2010-08-30  
6                0.38 2011-06-17  
7                 NaN 2011-06-18  
8                 NaN 2011-03-25  
9                0.38 2010-02-26  

[10 rows x 21 columns]

## Anova Tests

In [7]:
model = ols('Profit ~ C(Q("Order Priority"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Profit - Order Priority")
display(anova_table)


Anova => Sales - Order Priority


sum_sq      df         F    PR(>F)
C(Q("Order Priority"))  7.261269e+07     4.0  1.412692  0.226894
Residual                1.078634e+11  8394.0       NaN       NaN

Failed to reject null hypothesis, Order priority does not affect sales as there is no difference between their population means.

In [31]:
model = ols('Profit ~ C(Q("Order Priority"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Profit - Order Priority")
display(anova_table)


Anova => Profit - Order Priority


sum_sq      df         F    PR(>F)
C(Q("Order Priority"))  1.966864e+07     4.0  3.437807  0.008167
Residual                1.200609e+10  8394.0       NaN       NaN

We reject the null hypothesis which means that Profits are affected by the order priority as there is a difference in Profit means.

In [8]:
model = ols('Sales ~ C(Q("Ship Mode"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Sales - Ship Mode")
display(anova_table)


Anova => Sales - Ship Mode


sum_sq      df           F  PR(>F)
C(Q("Ship Mode"))  1.773769e+10     2.0  825.545281     0.0
Residual           9.019834e+10  8396.0         NaN     NaN

We reject the null hypothesis which means that sales are affected by the ship mode as there is a difference in sales and ship modes' population means.

In [9]:
model = ols('Sales ~ C(Q("Region"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Sales - Region")
display(anova_table)


Anova => Sales - Region


sum_sq      df         F    PR(>F)
C(Q("Region"))  1.028260e+08     7.0  1.143053  0.332599
Residual        1.078332e+11  8391.0       NaN       NaN

We fail to reject the null hypothesis which means that sales are not affected by the regions as there is no difference in sales and regions' population means.

In [10]:
model = ols('Sales ~ C(Q("Province"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Sales - Province")
display(anova_table)


Anova => Sales - Province


sum_sq      df         F    PR(>F)
C(Q("Province"))  2.081083e+08    12.0  1.350003  0.182509
Residual          1.077279e+11  8386.0       NaN       NaN

We fail to reject the null hypothesis which means that sales are not affected by the province as there is no difference in sales and province' population means.

In [11]:
model = ols('Sales ~ C(Q("Customer Segment"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Sales - Customer Segment")
display(anova_table)


Anova => Sales - Customer Segment


sum_sq      df         F    PR(>F)
C(Q("Customer Segment"))  2.238326e+07     3.0  0.580425  0.627813
Residual                  1.079136e+11  8395.0       NaN       NaN

We fail to reject the null hypothesis which means that sales are not affected by the customer segment as there is no difference in sales and customer segment' population means.

In [12]:
model = ols('Sales ~ C(Q("Product Category"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Sales - Product Category")
display(anova_table)


Anova => Sales - Product Category


sum_sq      df           F         PR(>F)
C(Q("Product Category"))  9.464206e+09     2.0  403.473146  4.908931e-168
Residual                  9.847182e+10  8396.0         NaN            NaN

We reject the null hypothesis which means that sales are affected by the category as there is a difference in sales and product category' population means.

In [13]:
model = ols('Sales ~ C(Q("Product Sub-Category"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Sales - Product Sub-Category")
display(anova_table)


Anova => Sales - Product Sub-Category


sum_sq      df          F  PR(>F)
C(Q("Product Sub-Category"))  3.410615e+10    16.0  242.00718     0.0
Residual                      7.382988e+10  8382.0        NaN     NaN

We  to reject the null hypothesis which means that sales are  affected by the product subcategory as there is a difference in sales and productsub category population means.

In [14]:
model = ols('Sales ~ C(Q("Product Container"))', data=salesdf).fit()
anova_table = sm.stats.anova_lm(model, typ=2)
print ("\nAnova => Sales - Product Container")
display(anova_table)


Anova => Sales - Product Container


sum_sq      df           F  PR(>F)
C(Q("Product Container"))  2.530821e+10     6.0  428.399995     0.0
Residual                   8.262781e+10  8392.0         NaN     NaN

We reject the null hypothesis which means that sales are affected by the product container as there is a difference in sales and product container' population means.

## Tukey Tests

In [15]:
salesdf['Ship Mode'].unique()

array(['Regular Air', 'Delivery Truck', 'Express Air'], dtype=object)

In [16]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

tukey = pairwise_tukeyhsd(endog=salesdf['Sales'],
                          groups=salesdf['Ship Mode'],
                          alpha=0.05)

#display results
print(tukey)

           Multiple Comparison of Means - Tukey HSD, FWER=0.05           
    group1        group2    meandiff  p-adj    lower      upper    reject
-------------------------------------------------------------------------
Delivery Truck Express Air -4226.9291    0.0 -4560.9404 -3892.9178   True
Delivery Truck Regular Air -4234.6538    0.0 -4481.4856  -3987.822   True
   Express Air Regular Air    -7.7247 0.9974  -271.2915   255.8421  False
-------------------------------------------------------------------------


row 1 and row 2 we reject there is a significant difference in means

In [17]:
salesdf['Product Category'].unique()

array(['Office Supplies', 'Technology', 'Furniture'], dtype=object)

In [18]:
tukey = pairwise_tukeyhsd(endog=salesdf['Sales'],
                          groups=salesdf['Product Category'],
                          alpha=0.05)

#display results
print(tukey)

             Multiple Comparison of Means - Tukey HSD, FWER=0.05              
     group1          group2      meandiff  p-adj    lower      upper    reject
------------------------------------------------------------------------------
      Furniture Office Supplies -2189.7746    0.0 -2416.4055 -1963.1438   True
      Furniture      Technology  -105.8818 0.6101  -367.7801   156.0165  False
Office Supplies      Technology  2083.8928    0.0  1871.3168  2296.4688   True
------------------------------------------------------------------------------


row 1 and row 3 we reject there is a significant difference in means

In [19]:
salesdf['Product Sub-Category'].unique()

array(['Storage & Organization', 'Appliances',
       'Binders and Binder Accessories', 'Telephones and Communication',
       'Office Furnishings', 'Paper', 'Rubber Bands',
       'Computer Peripherals', 'Envelopes', 'Bookcases', 'Tables',
       'Labels', 'Pens & Art Supplies', 'Copiers and Fax',
       'Chairs & Chairmats', 'Scissors, Rulers and Trimmers',
       'Office Machines'], dtype=object)

In [20]:
salesdf['Product Sub-Category'].nunique()

17

In [21]:
tukey = pairwise_tukeyhsd(endog=salesdf['Sales'],
                          groups=salesdf['Product Sub-Category'],
                          alpha=0.05)

#display results
print(tukey)

                              Multiple Comparison of Means - Tukey HSD, FWER=0.05                              
            group1                         group2               meandiff  p-adj     lower       upper    reject
---------------------------------------------------------------------------------------------------------------
                    Appliances Binders and Binder Accessories   -580.1508 0.0695  -1178.5716     18.2701  False
                    Appliances                      Bookcases   2654.5191    0.0   1759.7223   3549.3159   True
                    Appliances             Chairs & Chairmats   2866.2062    0.0   2147.8752   3584.5372   True
                    Appliances           Computer Peripherals   -648.1689 0.0285  -1266.2064    -30.1314   True
                    Appliances                Copiers and Fax  11294.5214    0.0  10088.4569   12500.586   True
                    Appliances                      Envelopes   -990.4713 0.0034  -1809.8756   -171.0671

Majority of appliances group row we reject there is a significant difference in means

In [22]:
tukey = pairwise_tukeyhsd(endog=salesdf['Sales'],
                          groups=salesdf['Product Container'],
                          alpha=0.05)

#display results
print(tukey)

        Multiple Comparison of Means - Tukey HSD, FWER=0.05         
  group1     group2    meandiff  p-adj    lower      upper    reject
--------------------------------------------------------------------
 Jumbo Box Jumbo Drum    155.259 0.9809  -390.8024   701.3205  False
 Jumbo Box  Large Box  -197.4478 0.9633  -807.2561   412.3605  False
 Jumbo Box Medium Box -3404.6195    0.0 -4033.0431 -2776.1958   True
 Jumbo Box  Small Box -4132.5012    0.0  -4557.537 -3707.4654   True
 Jumbo Box Small Pack -4731.2225    0.0 -5231.7494 -4230.6956   True
 Jumbo Box   Wrap Bag -5059.4642    0.0 -5543.4782 -4575.4501   True
Jumbo Drum  Large Box  -352.7068 0.5734  -942.7367   237.3231  False
Jumbo Drum Medium Box -3559.8785    0.0 -4169.1284 -2950.6286   True
Jumbo Drum  Small Box -4287.7603    0.0 -4683.8973 -3891.6232   True
Jumbo Drum Small Pack -4886.4816    0.0  -5362.713 -4410.2502   True
Jumbo Drum   Wrap Bag -5214.7232    0.0 -5673.5682 -4755.8782   True
 Large Box Medium Box -3207.1717  

we failed to reject row 1,2,7 and last as there is minimal difference in the means

## Chi-Squared Tests

In [23]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

# count of occurences of all combinations of the 2 columns
data_crosstab = pd.crosstab(salesdf['Customer Segment'], salesdf['Product Category'], 
margins = False) 
print(data_crosstab) 



Product Category  Furniture  Office Supplies  Technology
Customer Segment                                        
Consumer                358              865         426
Corporate               633             1680         763
Home Office             406             1145         481
Small Business          327              920         395


In [24]:
stat, p, dof, expected = chi2_contingency(data_crosstab)
print('dof=%d' % dof)
print(expected)

# interpret p-value
alpha = 0.05
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')


dof=6
[[ 338.47791404  905.09465413  405.42743184]
 [ 631.38754614 1688.33908799  756.27336588]
 [ 417.09346351 1115.31372782  499.59280867]
 [ 337.04107632  901.25253006  403.70639362]]
significance=0.050, p=0.349
Independent (fail to reject H0)


In [25]:
data_crosstab = pd.crosstab(salesdf['Product Container'], salesdf['Product Category'], 
margins = False) 
print(data_crosstab) 

stat, p, dof, expected = chi2_contingency(data_crosstab)
print('dof=%d' % dof)
print(expected)

# interpret p-value
alpha = 0.05
print('significance=%.3f, p=%.3f' % (alpha, p))
if p <= alpha:
    print('Dependent (reject H0)')
else:
    print('Independent (fail to reject H0)')


Product Category   Furniture  Office Supplies  Technology
Product Container                                        
Jumbo Box                488                0          44
Jumbo Drum               374               75         175
Large Box                164              160          82
Medium Box               119               89         158
Small Box                249             3059        1039
Small Pack               210              252         494
Wrap Bag                 120              975          73
dof=12
[[ 109.19966663  292.00142874  130.79890463]
 [ 128.0838195   342.49791642  153.41826408]
 [  83.33658769  222.84319562   99.82021669]
 [  75.12608644  200.88820098   89.98571258]
 [ 892.27622336 2385.95904274 1068.7647339 ]
 [ 196.23097988  524.72437195  235.04464817]
 [ 239.7466365   641.08584355  287.16751994]]
significance=0.050, p=0.000
Dependent (reject H0)


## t-tests

In [26]:
salesdf.dtypes

Row ID                           int64
Order ID                         int64
Order Date              datetime64[ns]
Order Priority                  object
Order Quantity                   int64
Sales                          float64
Discount                       float64
Ship Mode                       object
Profit                         float64
Unit Price                     float64
Shipping Cost                  float64
Customer Name                   object
Province                        object
Region                          object
Customer Segment                object
Product Category                object
Product Sub-Category            object
Product Name                    object
Product Container               object
Product Base Margin            float64
Ship Date               datetime64[ns]
dtype: object

In [27]:
#Extracts the data types of each column and stores them in a dictionary called types_map. 
#Then select data in numeric format to be kept in a num_columns list. 
# Allows to have the list of all numerical columns

types_map = salesdf.dtypes.to_dict()
num_columns = []
for k,v in types_map.items():
    if np.issubdtype(np.int64, v) or np.issubdtype(np.float64, v):
        num_columns.append(k)

print(num_columns)




['Row ID', 'Order ID', 'Order Quantity', 'Sales', 'Discount', 'Profit', 'Unit Price', 'Shipping Cost', 'Product Base Margin']


In [28]:
# independent two-sample t-test 
# The t-test is used to determine whether there is a significant difference between the means of these two samples.

t_val, p_val = stats.ttest_ind(salesdf[num_columns[3]], salesdf[num_columns[8]])
print("(Sales,Profit) => t-value=%s, p-value=%s" % (str(t_val), str(p_val)))

(Sales,Profit) => t-value=nan, p-value=nan


Nans? 

Possible that one or both of the samples being compared in the t-test contain missing values (NaNs). As a result, the t-test function (stats.ttest_ind) returns NaN values for the t-value and p-value. Attempt to remove the missing values to see the results. Hence, this highlights the importance of DATA WRANGLING before EDA.

In [29]:
salesdf[num_columns[3]].fillna(0, inplace=True)  # Fill missing values with 0
salesdf[num_columns[8]].fillna(0, inplace=True)

t_val, p_val = stats.ttest_ind(salesdf[num_columns[3]], salesdf[num_columns[8]])
print("(Sales,Profit) => t-value=%s, p-value=%s" % (str(t_val), str(p_val)))

(Sales,Profit) => t-value=45.38446985207996, p-value=0.0


Comparing 'Sales' and 'Profit' could be more appropriately approached using correlation analysis, such as Pearson correlation coefficient, which measures the linear relationship between two continuous variables.

Better example here could have been to compare a categorical variable with 2 categories VS Sales. Example, a comparison of gender and sales or if there were 2 categories however, we are limited to the columns available in this dataset. 